version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  php:
    container_name: php
    build:
      context: ./
    environment:
      PHP_IDE_CONFIG: "serverName=${SERVER_NAME}"
    volumes:
      - ./app:/app